# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94c79733bf04336892653ffcc1d94c462f6c202d4d94fc208ae17152c78f999dae22b3854850ba23813620d42347d3b8f3ed0406d5a01a6089bc47465f7f68cc

test:
  secret_key_base: b0ca1338d7502550c356a6eaeb56e5861b2a3ae0f7fc29469168112aefc4a1b62669b544a76f13a3949956d14b989e5209c624d111eb4e2f56b1709f1c598cd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
